export const FETCH_VACANCIES = 'FETCH_VACANCIES';
export const FETCH_VACANCY = 'FETCH_VACANCY';
export const FETCH_COMPANY_VACANCIES = 'FETCH_COMPANY_VACANCIES';
export const DELETE_VACANCY = 'DELETE_VACANCY';
